language: elixir
elixir:
  - 1.7
  - 1.8
otp_release:
  - 21.0
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
  - sudo apt-get install -qq libmp3lame-dev
  - export PKG_CONFIG_PATH=$(pwd)/ext
script:
  - mix format --check-formatted
  - mix espec
  - mix test
