version: 2.0
jobs:
  build:
    docker:
      - image: membraneframeworklabs/docker_membrane:latest
    environment:
      MIX_ENV: test
      PKG_CONFIG_PATH: '/root/app/ext/'
    working_directory: '~/app'

    steps:
      - checkout
      - run: apt-get update 
      - run: apt-get install -y libmp3lame-dev
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix espec
      - run: mix test
